namespace Waller.Native.App.ViewModels;

public sealed partial record LocalizedText
{
    public static LocalizedText Spanish { get; } = new(
        CurrentSetup: "Configuración actual",
        Monitors: "Monitores",
        DetectMonitors: "Detectar monitores",
        More: "Más",
        SelectMonitorToEdit: "Seleccioná un monitor para editar su fondo y color.",
        Preset: "Preset",
        PresetName: "Nombre del preset",
        Save: "Guardar",
        SaveAs: "Guardar como",
        Manage: "Gestionar",
        Refresh: "Actualizar",
        Settings: "Ajustes",
        ApplyAll: "Aplicar todo",
        Apply: "Aplicar",
        Edit: "Editar",
        EditMonitor: "Editar monitor",
        Source: "Fuente",
        ImagePath: "Ruta de imagen",
        ChooseImage: "Elegir imagen",
        Color: "Color",
        Fit: "Ajuste",
        Anchor: "Posición",
        PositionX: "Posición X",
        PositionY: "Posición Y",
        ResetPosition: "Restablecer posición",
        ManagePresets: "Gestionar Presets",
        ManagePresetsSubtitle: "Renombrar, duplicar o borrar presets locales.",
        SaveAsPresetSubtitle: "Crear un preset local desde la sesion actual.",
        NoPresetsSaved: "Todavia no hay presets guardados.",
        Close: "Cerrar",
        Rename: "Renombrar",
        Duplicate: "Duplicar",
        Delete: "Borrar",
        DeleteSelectedPreset: "¿Borrar el preset seleccionado?",
        DeleteSelectedPresetFormat: "¿Borrar {0}?",
        ConfirmDelete: "Confirmar borrado",
        SettingsSubtitle: "Tema, idioma y cache local.",
        Theme: "Tema",
        Language: "Idioma",
        ThemeSystem: "Sistema",
        ThemeLight: "Claro",
        ThemeDark: "Oscuro",
        LanguageEnglish: "Inglés",
        LanguageSpanish: "Español",
        ClearCache: "Limpiar caché",
        SaveSettings: "Guardar ajustes",
        MissingSourcePrefix: "Fuente faltante",
        ModifiedSuffix: "Modificado",
        DisconnectedSuffix: "desconectado",
        VisualOnlySuffix: "solo visual",
        NoMonitorSelected: "Ningún monitor seleccionado",
        NoMonitorsDetected: "No se detectaron monitores.",
        MissingMonitors: "Monitores desconectados",
        MissingMonitorsSubtitle: "Guardados en preset, pero no detectados ahora.",
        Forget: "Quitar",
        Reassign: "Reasignar",
        MissingSource: "Fuente faltante",
        EmptySource: "Vacio",
        ImageSource: "Imagen",
        ColorSource: "Color",
        Unsaved: "Sin guardar",
        Saved: "Guardado",
        Clean: "Limpio",
        Pending: "Pendiente",
        Applying: "Aplicando",
        Applied: "Aplicado",
        Error: "Error",
        CancelApply: "Cancelar",
        ApplyCancelled: "Aplicar cancelado.",
        ImageSelectionCancelled: "Selección de imagen cancelada.",
        SelectedImageFormat: "{0} seleccionado.",
        SkippedMissingSourceFormat: "{0} omitido por fuente faltante.",
        SavedPresetFormat: "Preset {0} guardado.",
        SavedNewPresetFormat: "Nuevo preset {0} guardado.",
        SaveAsOpened: "Guardar como abierto.",
        ManagePresetsOpened: "Gestión de presets abierta.",
        SelectPresetToRename: "Seleccioná un preset para renombrar.",
        PresetNameRequired: "El nombre del preset es requerido.",
        RenamedPresetFormat: "Preset renombrado a {0}.",
        SelectPresetToDuplicate: "Seleccioná un preset para duplicar.",
        PresetNotFound: "Preset no encontrado.",
        PresetNotFoundFormat: "Preset no encontrado: {0}.",
        PresetLoadFailed: "No se pudo cargar el preset. Actualiza presets e intenta de nuevo.",
        DuplicatedPresetFormat: "Preset duplicado como {0}.",
        SelectPresetToDelete: "Seleccioná un preset para borrar.",
        DeletedPresetKeptSession: "Preset borrado. La sesion activa queda sin cambios.",
        SettingsOpened: "Ajustes abiertos.",
        SettingsSaved: "Ajustes guardados.",
        LocalDataWriteFailed: "No se pudo escribir datos locales. Revisa permisos de carpeta e intenta de nuevo.",
        RenderedCacheClearedFormat: "Cache renderizada limpiada. {0} archivo(s) borrados.",
        RenderedCachePartiallyClearedFormat: "Cache renderizada limpiada parcialmente. {0} archivo(s) borrados, {1} omitidos.",
        InvalidEditValueFormat: "Valor inválido: {0}",
        InvalidColor: "El color debe usar #RRGGBB.",
        ImagePathRequired: "La ruta de imagen es requerida.",
        ImagePathMustBeFull: "Usa una ruta completa de imagen.",
        ImagePathUnsupportedFileType: "Usa un tipo de archivo de imagen compatible.",
        CheckValue: "Revisa el valor e intenta de nuevo.",
        RenderedWallpaperMissing: "Falta el wallpaper renderizado.",
        WallpaperApplyFailed: "Windows no pudo aplicar el wallpaper.",
        UnknownApplyError: "Aplicar fallo para este monitor.",
        ForgotDisconnectedMonitorFormat: "Monitor desconectado {0} quitado. Guarda el preset para conservar el cambio.",
        ReassignedDisconnectedMonitorFormat: "Monitor desconectado {0} reasignado a {1}. Guarda el preset para conservar el cambio.",
        SelectMonitorBeforeReassign: "Seleccioná un monitor actual antes de reasignar.",
        PendingChangesFormat: "{0} tiene cambios pendientes.",
        LoadedCurrentSetup: "Configuración actual de Windows cargada.",
        CurrentSetupRefreshed: "Configuración actual de Windows actualizada.",
        MonitorCountFormat: "{0} monitor(es).",
        WindowsDetectionFallback: "Falló la detección de monitores de Windows; se muestra el estado sin monitores.",
        StartupFailed: "Falló el inicio. Reiniciá Waller o revisá los permisos de datos locales.",
        CurrentSetupSelected: "Configuración actual seleccionada. Windows no cambió.",
        LoadedPresetFormat: "Preset {0} cargado. Windows no cambió.",
        PreparingApply: "Preparando Aplicar...",
        NothingToApply: "Nada para aplicar.",
        NothingApplied: "Nada aplicado.",
        ApplyUnexpectedFailure: "Aplicar falló de forma inesperada. Revisá las imágenes y permisos de Windows e intentá de nuevo.",
        ApplyFinishedFormat: "Aplicar terminó. {0} correctos, {1} con error.",
        FitCover: "Cubrir",
        FitContain: "Contener",
        FitStretch: "Estirar",
        FitCenter: "Centrar",
        FitTile: "Mosaico",
        AnchorTopLeft: "Arriba izquierda",
        AnchorTop: "Arriba",
        AnchorTopRight: "Arriba derecha",
        AnchorLeft: "Izquierda",
        AnchorCenter: "Centro",
        AnchorRight: "Derecha",
        AnchorBottomLeft: "Abajo izquierda",
        AnchorBottom: "Abajo",
        AnchorBottomRight: "Abajo derecha",
        UnsupportedValue: "Valor no compatible",
        OffsetSummaryFormat: "Posición {0}, {1}");
}
