namespace Waller.Native.App.ViewModels;

public sealed partial record LocalizedText
{
    public static LocalizedText English { get; } = new(
        CurrentSetup: "Current setup",
        Monitors: "Monitors",
        DetectMonitors: "Detect monitors",
        More: "More",
        SelectMonitorToEdit: "Select a monitor to edit its wallpaper and color.",
        Preset: "Preset",
        PresetName: "Preset name",
        Save: "Save",
        SaveAs: "Save as",
        Manage: "Manage",
        Refresh: "Refresh",
        Settings: "Settings",
        ApplyAll: "Apply all",
        Apply: "Apply",
        Edit: "Edit",
        EditMonitor: "Edit monitor",
        Source: "Source",
        ImagePath: "Image path",
        ChooseImage: "Choose image",
        Color: "Color",
        Fit: "Fit",
        Anchor: "Anchor",
        PositionX: "Position X",
        PositionY: "Position Y",
        ResetPosition: "Reset position",
        ManagePresets: "Manage Presets",
        ManagePresetsSubtitle: "Rename, duplicate, or delete local presets.",
        SaveAsPresetSubtitle: "Create a local preset from the current session.",
        NoPresetsSaved: "No presets saved yet.",
        Close: "Close",
        Rename: "Rename",
        Duplicate: "Duplicate",
        Delete: "Delete",
        DeleteSelectedPreset: "Delete selected preset?",
        DeleteSelectedPresetFormat: "Delete {0}?",
        ConfirmDelete: "Confirm delete",
        SettingsSubtitle: "Theme, language, and local cache.",
        Theme: "Theme",
        Language: "Language",
        ThemeSystem: "System",
        ThemeLight: "Light",
        ThemeDark: "Dark",
        LanguageEnglish: "English",
        LanguageSpanish: "Spanish",
        ClearCache: "Clear cache",
        SaveSettings: "Save settings",
        MissingSourcePrefix: "Missing source",
        ModifiedSuffix: "Modified",
        DisconnectedSuffix: "disconnected",
        VisualOnlySuffix: "visual only",
        NoMonitorSelected: "No monitor selected",
        NoMonitorsDetected: "No monitors detected.",
        MissingMonitors: "Disconnected monitors",
        MissingMonitorsSubtitle: "Saved in preset but not currently detected.",
        Forget: "Forget",
        Reassign: "Reassign",
        MissingSource: "Missing source",
        EmptySource: "Empty",
        ImageSource: "Image",
        ColorSource: "Color",
        Unsaved: "Unsaved",
        Saved: "Saved",
        Clean: "Clean",
        Pending: "Pending",
        Applying: "Applying",
        Applied: "Applied",
        Error: "Error",
        CancelApply: "Cancel",
        ApplyCancelled: "Apply cancelled.",
        ImageSelectionCancelled: "Image selection cancelled.",
        SelectedImageFormat: "Selected {0}.",
        SkippedMissingSourceFormat: "{0} skipped for missing source.",
        SavedPresetFormat: "Saved preset {0}.",
        SavedNewPresetFormat: "Saved new preset {0}.",
        SaveAsOpened: "Save as opened.",
        ManagePresetsOpened: "Manage Presets opened.",
        SelectPresetToRename: "Select a preset to rename.",
        PresetNameRequired: "Preset name is required.",
        RenamedPresetFormat: "Renamed preset to {0}.",
        SelectPresetToDuplicate: "Select a preset to duplicate.",
        PresetNotFound: "Preset not found.",
        PresetNotFoundFormat: "Preset not found: {0}.",
        PresetLoadFailed: "Could not load preset. Refresh presets and try again.",
        DuplicatedPresetFormat: "Duplicated preset as {0}.",
        SelectPresetToDelete: "Select a preset to delete.",
        DeletedPresetKeptSession: "Deleted preset. Active Session kept unchanged.",
        SettingsOpened: "Settings opened.",
        SettingsSaved: "Settings saved.",
        LocalDataWriteFailed: "Could not write local app data. Check folder permissions and try again.",
        RenderedCacheClearedFormat: "Rendered cache cleared. {0} file(s) deleted.",
        RenderedCachePartiallyClearedFormat: "Rendered cache partially cleared. {0} file(s) deleted, {1} skipped.",
        InvalidEditValueFormat: "Invalid value: {0}",
        InvalidColor: "Color must use #RRGGBB.",
        ImagePathRequired: "Image path is required.",
        ImagePathMustBeFull: "Use a full image path.",
        ImagePathUnsupportedFileType: "Use a supported image file type.",
        CheckValue: "Check the value and try again.",
        RenderedWallpaperMissing: "Rendered wallpaper is missing.",
        WallpaperApplyFailed: "Windows could not apply the wallpaper.",
        UnknownApplyError: "Apply failed for this monitor.",
        ForgotDisconnectedMonitorFormat: "Forgot disconnected monitor {0}. Save preset to keep this change.",
        ReassignedDisconnectedMonitorFormat: "Reassigned disconnected monitor {0} to {1}. Save preset to keep this change.",
        SelectMonitorBeforeReassign: "Select a current monitor before reassigning.",
        PendingChangesFormat: "{0} has pending changes.",
        LoadedCurrentSetup: "Loaded current Windows setup.",
        CurrentSetupRefreshed: "Current Windows setup refreshed.",
        MonitorCountFormat: "{0} monitor(s).",
        WindowsDetectionFallback: "Windows monitor detection failed; showing empty monitor state.",
        StartupFailed: "Startup failed. Restart Waller or check local app data permissions.",
        CurrentSetupSelected: "Current setup selected. Windows was not changed.",
        LoadedPresetFormat: "Loaded preset {0}. Windows was not changed.",
        PreparingApply: "Preparing Apply...",
        NothingToApply: "Nothing to apply.",
        NothingApplied: "Nothing applied.",
        ApplyUnexpectedFailure: "Apply failed unexpectedly. Check source files and Windows permissions, then try again.",
        ApplyFinishedFormat: "Apply finished. {0} succeeded, {1} failed.",
        FitCover: "Cover",
        FitContain: "Contain",
        FitStretch: "Stretch",
        FitCenter: "Center",
        FitTile: "Tile",
        AnchorTopLeft: "Top left",
        AnchorTop: "Top",
        AnchorTopRight: "Top right",
        AnchorLeft: "Left",
        AnchorCenter: "Center",
        AnchorRight: "Right",
        AnchorBottomLeft: "Bottom left",
        AnchorBottom: "Bottom",
        AnchorBottomRight: "Bottom right",
        UnsupportedValue: "Unsupported value",
        OffsetSummaryFormat: "Position {0}, {1}");
}
