using Waller.Native.Core.Settings;

namespace Waller.Native.App.ViewModels;

public sealed partial record LocalizedText
{
    public static LocalizedText For(string language) =>
        string.Equals(language, AppLanguages.Spanish, StringComparison.OrdinalIgnoreCase)
            ? Spanish
            : English;

    public static LocalizedText English { get; } = new(
        "Current setup",
        "Preset",
        "Preset name",
        "Save",
        "Save as",
        "Manage",
        "Refresh",
        "Settings",
        "Apply all",
        "Apply",
        "Edit",
        "Edit monitor",
        "Source",
        "Image path",
        "Choose image",
        "Color",
        "Fit",
        "Anchor",
        "Position X",
        "Position Y",
        "Reset position",
        "Manage Presets",
        "Rename, duplicate, or delete local presets.",
        "Create a local preset from the current session.",
        "No presets saved yet.",
        "Close",
        "Rename",
        "Duplicate",
        "Delete",
        "Delete selected preset?",
        "Delete {0}?",
        "Confirm delete",
        "Theme, language, and local cache.",
        "Theme",
        "Language",
        "System",
        "Light",
        "Dark",
        "English",
        "Spanish",
        "Clear cache",
        "Save settings",
        "Missing source",
        "Modified",
        "disconnected",
        "visual only",
        "No monitor selected",
        "No monitors detected.",
        "Disconnected monitors",
        "Saved in preset but not currently detected.",
        "Forget",
        "Reassign",
        "Missing source",
        "Empty",
        "Image",
        "Color",
        "Unsaved",
        "Saved",
        "Clean",
        "Pending",
        "Applying",
        "Applied",
        "Error",
        "Cancel",
        "Apply cancelled.",
        "Image selection cancelled.",
        "Selected {0}.",
        "{0} skipped for missing source.",
        "Saved preset {0}.",
        "Saved new preset {0}.",
        "Save as opened.",
        "Manage Presets opened.",
        "Select a preset to rename.",
        "Preset name is required.",
        "Renamed preset to {0}.",
        "Select a preset to duplicate.",
        "Preset not found.",
        "Preset not found: {0}.",
        "Could not load preset. Refresh presets and try again.",
        "Duplicated preset as {0}.",
        "Select a preset to delete.",
        "Deleted preset. Active Session kept unchanged.",
        "Settings opened.",
        "Settings saved.",
        "Could not write local app data. Check folder permissions and try again.",
        "Rendered cache cleared. {0} file(s) deleted.",
        "Rendered cache partially cleared. {0} file(s) deleted, {1} skipped.",
        "Invalid value: {0}",
        "Color must use #RRGGBB.",
        "Image path is required.",
        "Use a full image path.",
        "Use a supported image file type.",
        "Check the value and try again.",
        "Rendered wallpaper is missing.",
        "Windows could not apply the wallpaper.",
        "Forgot disconnected monitor {0}. Save preset to keep this change.",
        "Reassigned disconnected monitor {0} to {1}. Save preset to keep this change.",
        "Select a current monitor before reassigning.",
        "{0} has pending changes.",
        "Loaded current Windows setup.",
        "Current Windows setup refreshed.",
        "{0} monitor(s).",
        "Windows monitor detection failed; showing empty monitor state.",
        "Startup failed. Restart Waller or check local app data permissions.",
        "Current setup selected. Windows was not changed.",
        "Loaded preset {0}. Windows was not changed.",
        "Preparing Apply...",
        "Nothing to apply.",
        "Nothing applied.",
        "Apply failed unexpectedly. Check source files and Windows permissions, then try again.",
        "Apply finished. {0} succeeded, {1} failed.");

    public static LocalizedText Spanish { get; } = new(
        "Configuracion actual",
        "Preset",
        "Nombre del preset",
        "Guardar",
        "Guardar como",
        "Gestionar",
        "Actualizar",
        "Ajustes",
        "Aplicar todo",
        "Aplicar",
        "Editar",
        "Editar monitor",
        "Fuente",
        "Ruta de imagen",
        "Elegir imagen",
        "Color",
        "Ajuste",
        "Posicion",
        "Posicion X",
        "Posicion Y",
        "Restablecer posicion",
        "Gestionar Presets",
        "Renombrar, duplicar o borrar presets locales.",
        "Crear un preset local desde la sesion actual.",
        "Todavia no hay presets guardados.",
        "Cerrar",
        "Renombrar",
        "Duplicar",
        "Borrar",
        "Borrar preset seleccionado?",
        "Borrar {0}?",
        "Confirmar borrado",
        "Tema, idioma y cache local.",
        "Tema",
        "Idioma",
        "Sistema",
        "Claro",
        "Oscuro",
        "Ingles",
        "Espanol",
        "Limpiar cache",
        "Guardar ajustes",
        "Fuente faltante",
        "Modificado",
        "desconectado",
        "solo visual",
        "Ningun monitor seleccionado",
        "No se detectaron monitores.",
        "Monitores desconectados",
        "Guardados en preset, pero no detectados ahora.",
        "Quitar",
        "Reasignar",
        "Fuente faltante",
        "Vacio",
        "Imagen",
        "Color",
        "Sin guardar",
        "Guardado",
        "Limpio",
        "Pendiente",
        "Aplicando",
        "Aplicado",
        "Error",
        "Cancelar",
        "Aplicar cancelado.",
        "Seleccion de imagen cancelada.",
        "{0} seleccionado.",
        "{0} omitido por fuente faltante.",
        "Preset {0} guardado.",
        "Nuevo preset {0} guardado.",
        "Guardar como abierto.",
        "Gestion de Presets abierta.",
        "Selecciona un preset para renombrar.",
        "El nombre del preset es requerido.",
        "Preset renombrado a {0}.",
        "Selecciona un preset para duplicar.",
        "Preset no encontrado.",
        "Preset no encontrado: {0}.",
        "No se pudo cargar el preset. Actualiza presets e intenta de nuevo.",
        "Preset duplicado como {0}.",
        "Selecciona un preset para borrar.",
        "Preset borrado. La sesion activa queda sin cambios.",
        "Ajustes abiertos.",
        "Ajustes guardados.",
        "No se pudo escribir datos locales. Revisa permisos de carpeta e intenta de nuevo.",
        "Cache renderizada limpiada. {0} archivo(s) borrados.",
        "Cache renderizada limpiada parcialmente. {0} archivo(s) borrados, {1} omitidos.",
        "Valor invalido: {0}",
        "El color debe usar #RRGGBB.",
        "La ruta de imagen es requerida.",
        "Usa una ruta completa de imagen.",
        "Usa un tipo de archivo de imagen compatible.",
        "Revisa el valor e intenta de nuevo.",
        "Falta el wallpaper renderizado.",
        "Windows no pudo aplicar el wallpaper.",
        "Monitor desconectado {0} quitado. Guarda el preset para conservar el cambio.",
        "Monitor desconectado {0} reasignado a {1}. Guarda el preset para conservar el cambio.",
        "Selecciona un monitor actual antes de reasignar.",
        "{0} tiene cambios pendientes.",
        "Configuracion actual de Windows cargada.",
        "Configuracion actual de Windows actualizada.",
        "{0} monitor(es).",
        "Fallo deteccion de monitores Windows; se muestra estado sin monitores.",
        "Fallo el inicio. Reinicia Waller o revisa permisos de datos locales.",
        "Configuracion actual seleccionada. Windows no cambio.",
        "Preset {0} cargado. Windows no cambio.",
        "Preparando Aplicar...",
        "Nada para aplicar.",
        "Nada aplicado.",
        "Aplicar fallo inesperadamente. Revisa las imagenes y permisos de Windows, e intenta de nuevo.",
        "Aplicar terminado. {0} OK, {1} fallaron.");
}
