using Waller.Native.Core.Settings;

namespace Waller.Native.App.ViewModels;

public sealed partial record LocalizedText(
    string CurrentSetup,
    string Monitors,
    string DetectMonitors,
    string More,
    string SelectMonitorToEdit,
    string Preset,
    string PresetName,
    string Save,
    string SaveAs,
    string Manage,
    string Refresh,
    string Settings,
    string ApplyAll,
    string Apply,
    string Edit,
    string EditMonitor,
    string Source,
    string ImagePath,
    string ChooseImage,
    string Color,
    string Fit,
    string Anchor,
    string PositionX,
    string PositionY,
    string ResetPosition,
    string ManagePresets,
    string ManagePresetsSubtitle,
    string SaveAsPresetSubtitle,
    string NoPresetsSaved,
    string Close,
    string Rename,
    string Duplicate,
    string Delete,
    string DeleteSelectedPreset,
    string DeleteSelectedPresetFormat,
    string ConfirmDelete,
    string SettingsSubtitle,
    string Theme,
    string Language,
    string ThemeSystem,
    string ThemeLight,
    string ThemeDark,
    string LanguageEnglish,
    string LanguageSpanish,
    string ClearCache,
    string SaveSettings,
    string MissingSourcePrefix,
    string ModifiedSuffix,
    string DisconnectedSuffix,
    string VisualOnlySuffix,
    string NoMonitorSelected,
    string NoMonitorsDetected,
    string MissingMonitors,
    string MissingMonitorsSubtitle,
    string Forget,
    string Reassign,
    string MissingSource,
    string EmptySource,
    string ImageSource,
    string ColorSource,
    string Unsaved,
    string Saved,
    string Clean,
    string Pending,
    string Applying,
    string Applied,
    string Error,
    string CancelApply,
    string ApplyCancelled,
    string ImageSelectionCancelled,
    string SelectedImageFormat,
    string SkippedMissingSourceFormat,
    string SavedPresetFormat,
    string SavedNewPresetFormat,
    string SaveAsOpened,
    string ManagePresetsOpened,
    string SelectPresetToRename,
    string PresetNameRequired,
    string RenamedPresetFormat,
    string SelectPresetToDuplicate,
    string PresetNotFound,
    string PresetNotFoundFormat,
    string PresetLoadFailed,
    string DuplicatedPresetFormat,
    string SelectPresetToDelete,
    string DeletedPresetKeptSession,
    string SettingsOpened,
    string SettingsSaved,
    string LocalDataWriteFailed,
    string RenderedCacheClearedFormat,
    string RenderedCachePartiallyClearedFormat,
    string InvalidEditValueFormat,
    string InvalidColor,
    string ImagePathRequired,
    string ImagePathMustBeFull,
    string ImagePathUnsupportedFileType,
    string CheckValue,
    string RenderedWallpaperMissing,
    string WallpaperApplyFailed,
    string UnknownApplyError,
    string ForgotDisconnectedMonitorFormat,
    string ReassignedDisconnectedMonitorFormat,
    string SelectMonitorBeforeReassign,
    string PendingChangesFormat,
    string LoadedCurrentSetup,
    string CurrentSetupRefreshed,
    string MonitorCountFormat,
    string WindowsDetectionFallback,
    string StartupFailed,
    string CurrentSetupSelected,
    string LoadedPresetFormat,
    string PreparingApply,
    string NothingToApply,
    string NothingApplied,
    string ApplyUnexpectedFailure,
    string ApplyFinishedFormat,
    string FitCover,
    string FitContain,
    string FitStretch,
    string FitCenter,
    string FitTile,
    string AnchorTopLeft,
    string AnchorTop,
    string AnchorTopRight,
    string AnchorLeft,
    string AnchorCenter,
    string AnchorRight,
    string AnchorBottomLeft,
    string AnchorBottom,
    string AnchorBottomRight,
    string UnsupportedValue,
    string OffsetSummaryFormat)
{
    public string Format(string format, params object[] args)
    {
        ArgumentNullException.ThrowIfNull(format);
        ArgumentNullException.ThrowIfNull(args);

        return string.Format(
            AppLanguages.CultureFor(IsSpanish ? AppLanguages.Spanish : AppLanguages.English),
            format,
            args);
    }

    internal bool IsSpanish => ReferenceEquals(this, Spanish);
}
